# Generated by Django 4.2.1 on 2023-06-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(max_length=15)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
