# Generated by Django 4.2.1 on 2023-06-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('comandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandas',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
            preserve_default=False,
        ),
    ]
