# Generated by Django 4.2.1 on 2023-06-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0003_clientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'Comandas'},
        ),
    ]
