# Generated by Django 4.2.1 on 2023-06-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0004_alter_clientes_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.RemoveField(
            model_name='comandas',
            name='cliente',
        ),
    ]
