# Generated by Django 4.2.1 on 2023-06-07 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_merge_0002_alter_clientes_options_0002_clientes_saldo'),
        ('comandas', '0005_delete_clientes_remove_comandas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandas',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
            preserve_default=False,
        ),
    ]
