# Generated by Django 4.2.1 on 2023-06-07 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0006_comandas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandas',
            name='data_atual',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
