# Generated by Django 4.2.1 on 2023-06-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0008_rename_data_atual_comandas_ultima_recarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandas',
            name='forma_pagamento',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
