# Generated by Django 4.2.1 on 2023-06-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_options'),
        ('clientes', '0002_clientes_saldo'),
    ]

    operations = [
    ]
