# Generated by Django 4.2.1 on 2023-06-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_merge_0002_alter_clientes_options_0002_clientes_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='saldo',
        ),
    ]
